/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vanes
 */
public class FrmPizzaMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form FrmPizzaMainScreen
     */
    public FrmPizzaMainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblaskdiameter = new javax.swing.JLabel();
        iconanchovies = new javax.swing.JLabel();
        iconolives = new javax.swing.JLabel();
        lblpizzatitle = new javax.swing.JLabel();
        btn_calculatepizza = new javax.swing.JButton();
        txtdiameter_of_pizza = new javax.swing.JTextField();
        lblsubtotal = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        lbltax = new javax.swing.JLabel();
        txttax = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        txtpizzamessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblaskdiameter.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lblaskdiameter.setText("Diameter of Pizza (CM):");

        iconanchovies.setIcon(new javax.swing.ImageIcon("C:\\Users\\vanes\\OneDrive\\Desktop\\cuteanchovycrop.jpg")); // NOI18N
        iconanchovies.setText("jLabel2");

        iconolives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconolives.setIcon(new javax.swing.ImageIcon("C:\\Users\\vanes\\OneDrive\\Desktop\\olivecrop.jpg")); // NOI18N
        iconolives.setText("jLabel3");

        lblpizzatitle.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lblpizzatitle.setText("Putrid Pizza!");

        btn_calculatepizza.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        btn_calculatepizza.setText("Calculate");
        btn_calculatepizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculatepizzaActionPerformed(evt);
            }
        });

        txtdiameter_of_pizza.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        txtdiameter_of_pizza.setText("0");

        lblsubtotal.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lblsubtotal.setText("Subtotal:      $");

        txtsubtotal.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        txtsubtotal.setText("0.00");

        lbltax.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lbltax.setText("Taxes (13%):      $");

        txttax.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        txttax.setText("0.00");

        lbltotal.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lbltotal.setText("Grand Total:      $");

        txttotal.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        txttotal.setText("0.00");

        txtpizzamessage.setFont(new java.awt.Font("Arial Black", 0, 19)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconanchovies, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconolives, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblaskdiameter)
                        .addContainerGap(356, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpizzamessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblsubtotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbltotal)
                                            .addComponent(lbltax))
                                        .addGap(7, 7, 7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdiameter_of_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txttax, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblpizzatitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_calculatepizza)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(txtpizzamessage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblaskdiameter)
                            .addComponent(txtdiameter_of_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addComponent(btn_calculatepizza)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconanchovies, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblpizzatitle)
                        .addGap(84, 84, 84)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsubtotal)
                            .addComponent(txtsubtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltax)
                            .addComponent(txttax))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltotal)
                            .addComponent(txttotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(iconolives, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calculatepizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculatepizzaActionPerformed
        // TODO add your handling code here:
        // constant variables
        
        final double LABOUR_CHARGE = 0.75;
        final double RENT = 0.99;
        final double PER_DIAMETER_CM = 0.50;
        final double TAX_PERCENTAGE = 0.13;
        
        // variable that will store the user's inputed pizza diameter
        
        double pizza_diameter;
        
        // pizza message variable
        String pizzamessage;
        // subtotal, tax, and grand total variables
        
        double subtotal;
        double tax;
        double grand_total;
        
        // connecting my pizza_diameter variable to the approriate text box so I can save what the user inputs (and use it to calculate the price of the pizza)
        pizza_diameter = Double.parseDouble(txtdiameter_of_pizza.getText());
        
        // calculating the subtotal using the constants and pizza diameter
        // adding an if and else statment if the pizza diameter is 0
        if(pizza_diameter == 0){
            subtotal = 0;
        }
        else{
            subtotal = (PER_DIAMETER_CM * pizza_diameter) + LABOUR_CHARGE + RENT;
        }
        // round the subtotal using Math.round()
        subtotal = Math.round(subtotal * 100.0) / 100.0;
        // displays the subtotal on the GUI
        txtsubtotal.setText(String.valueOf(subtotal));
        
        // calculating the tax based on the subtotal
        tax = subtotal * TAX_PERCENTAGE;
        // round the tax using Math.round()
        tax= Math.round(tax * 100.0) / 100.0;
        // displays the tax on the GUI
        txttax.setText(String.valueOf(tax));
        
        // calculating the total by adding the subtotal and tax
        grand_total = subtotal + tax;
        // round the total using Math.round()
        grand_total = Math.round(grand_total * 100.0) / 100.0;
        // displays the total on the GUI
        txttotal.setText(String.valueOf(grand_total));
        
        if (pizza_diameter >= 1 && pizza_diameter < 16){
            pizzamessage = "We are going to make you a cute little pizza!";
        }
        else if (pizza_diameter > 20 && pizza_diameter < 40){
            pizzamessage = "This will be delicious!";
        }
        else if (pizza_diameter > 40){
            pizzamessage = "Whoa, big pizza! You might need a truck to get this home!";
        }
        else{
            pizzamessage = "";
        }
        txtpizzamessage.setText(String.valueOf(pizzamessage));
        
    }//GEN-LAST:event_btn_calculatepizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPizzaMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculatepizza;
    private javax.swing.JLabel iconanchovies;
    private javax.swing.JLabel iconolives;
    private javax.swing.JLabel lblaskdiameter;
    private javax.swing.JLabel lblpizzatitle;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltax;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtdiameter_of_pizza;
    private javax.swing.JLabel txtpizzamessage;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txttax;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
